=== yabfc/yabfc/profiles/schema.json
{
	"$ref": "#/definitions/ProfileInterface",
	"$schema": "http://json-schema.org/draft-07/schema#",
	"definitions": {
		"ProfileInterface": {
			"additionalProperties": false,
			"properties": {
				"id": {
					"type": "string"
				},
				"items": {
					"items": {
						"additionalProperties": false,
						"properties": {
							"category": {
								"type": "string"
							},
							"id": {
								"type": "string"
							},
							"name": {
								"type": "string"
							},
							"stackSize": {
								"type": "number"
							},
							"type": {
								"enum": ["item", "fluid"],
								"type": "string"
							}
						},
						"required": ["id", "type", "category", "stackSize"],
						"type": "object"
					},
					"type": "array"
				},
				"logistics": {
					"items": {
						"additionalProperties": false,
						"properties": {
							"features": {
								"items": {
									"additionalProperties": false,
									"properties": {
										"effectPerSlot": {
											"items": {
												"type": "string"
											},
											"type": "array"
										},
										"hidden": {
											"type": "boolean"
										},
										"id": {
											"type": "string"
										},
										"itemSlots": {
											"type": "number"
										},
										"modifiable": {
											"type": "boolean"
										},
										"name": {
											"type": "string"
										}
									},
									"required": ["id", "itemSlots", "effectPerSlot"],
									"type": "object"
								},
								"type": "array"
							},
							"id": {
								"type": "string"
							},
							"speed": {
								"type": "number"
							},
							"type": {
								"enum": ["item", "fluid"],
								"type": "string"
							}
						},
						"required": ["id", "type", "speed"],
						"type": "object"
					},
					"type": "array"
				},
				"machineEffects": {
					"items": {
						"anyOf": [
							{
								"additionalProperties": false,
								"properties": {
									"allowedEffects": {
										"items": {
											"type": "string"
										},
										"type": "array"
									},
									"available": {
										"type": "boolean"
									},
									"displayOffset": {
										"type": "number"
									},
									"hidden": {
										"type": "boolean"
									},
									"id": {
										"type": "string"
									},
									"modifiers": {
										"items": {
											"additionalProperties": false,
											"properties": {
												"id": {
													"enum": [
														"speed",
														"power",
														"consumption",
														"productivity",
														"pollution",
														"quality"
													],
													"type": "string"
												},
												"name": {
													"type": "string"
												},
												"value": {
													"type": "number"
												},
												"valueScaling": {
													"enum": ["exponential", "squared"],
													"type": "string"
												}
											},
											"required": ["id", "value"],
											"type": "object"
										},
										"type": "array"
									},
									"name": {
										"type": "string"
									},
									"singleUse": {
										"type": "boolean"
									},
									"type": {
										"const": "fixed",
										"type": "string"
									}
								},
								"required": ["available", "id", "modifiers", "type"],
								"type": "object"
							},
							{
								"additionalProperties": false,
								"properties": {
									"allowedEffects": {
										"items": {
											"type": "string"
										},
										"type": "array"
									},
									"available": {
										"type": "boolean"
									},
									"displayOffset": {
										"type": "number"
									},
									"hidden": {
										"type": "boolean"
									},
									"id": {
										"type": "string"
									},
									"maxValue": {
										"type": "number"
									},
									"minValue": {
										"type": "number"
									},
									"modifiers": {
										"items": {
											"additionalProperties": false,
											"properties": {
												"id": {
													"enum": [
														"speed",
														"power",
														"consumption",
														"productivity",
														"pollution",
														"quality"
													],
													"type": "string"
												},
												"name": {
													"type": "string"
												},
												"value": {
													"type": "number"
												},
												"valueScaling": {
													"enum": ["exponential", "squared"],
													"type": "string"
												}
											},
											"required": ["id", "value"],
											"type": "object"
										},
										"type": "array"
									},
									"name": {
										"type": "string"
									},
									"singleUse": {
										"type": "boolean"
									},
									"step": {
										"type": "number"
									},
									"type": {
										"const": "stepped",
										"type": "string"
									}
								},
								"required": [
									"available",
									"id",
									"maxValue",
									"minValue",
									"modifiers",
									"step",
									"type"
								],
								"type": "object"
							},
							{
								"additionalProperties": false,
								"properties": {
									"allowedEffects": {
										"items": {
											"type": "string"
										},
										"type": "array"
									},
									"available": {
										"type": "boolean"
									},
									"displayOffset": {
										"type": "number"
									},
									"hidden": {
										"type": "boolean"
									},
									"id": {
										"type": "string"
									},
									"maxValue": {
										"type": "number"
									},
									"minValue": {
										"type": "number"
									},
									"modifiers": {
										"items": {
											"additionalProperties": false,
											"properties": {
												"id": {
													"enum": [
														"speed",
														"power",
														"consumption",
														"productivity",
														"pollution",
														"quality"
													],
													"type": "string"
												},
												"name": {
													"type": "string"
												},
												"value": {
													"type": "number"
												},
												"valueScaling": {
													"enum": ["exponential", "squared"],
													"type": "string"
												}
											},
											"required": ["id", "value"],
											"type": "object"
										},
										"type": "array"
									},
									"name": {
										"type": "string"
									},
									"singleUse": {
										"type": "boolean"
									},
									"type": {
										"const": "modifiable",
										"type": "string"
									}
								},
								"required": ["available", "id", "maxValue", "minValue", "modifiers", "type"],
								"type": "object"
							},
							{
								"additionalProperties": false,
								"properties": {
									"allowedEffects": {
										"items": {
											"type": "string"
										},
										"type": "array"
									},
									"available": {
										"type": "boolean"
									},
									"displayOffset": {
										"type": "number"
									},
									"hidden": {
										"type": "boolean"
									},
									"id": {
										"type": "string"
									},
									"maxValue": {
										"type": "number"
									},
									"minValue": {
										"type": "number"
									},
									"modifiers": {
										"items": {
											"additionalProperties": false,
											"properties": {
												"id": {
													"enum": [
														"speed",
														"power",
														"consumption",
														"productivity",
														"pollution",
														"quality"
													],
													"type": "string"
												},
												"name": {
													"type": "string"
												},
												"value": {
													"type": "number"
												},
												"valueScaling": {
													"enum": ["exponential", "squared"],
													"type": "string"
												}
											},
											"required": ["id", "value"],
											"type": "object"
										},
										"type": "array"
									},
									"name": {
										"type": "string"
									},
									"singleUse": {
										"type": "boolean"
									},
									"type": {
										"const": "limited",
										"type": "string"
									}
								},
								"required": ["available", "id", "modifiers", "type"],
								"type": "object"
							}
						]
					},
					"type": "array"
				},
				"machines": {
					"items": {
						"additionalProperties": false,
						"properties": {
							"available": {
								"type": "boolean"
							},
							"features": {
								"items": {
									"additionalProperties": false,
									"properties": {
										"effectPerSlot": {
											"items": {
												"type": "string"
											},
											"type": "array"
										},
										"hidden": {
											"type": "boolean"
										},
										"id": {
											"type": "string"
										},
										"itemSlots": {
											"type": "number"
										},
										"modifiable": {
											"type": "boolean"
										},
										"name": {
											"type": "string"
										}
									},
									"required": ["id", "itemSlots", "effectPerSlot"],
									"type": "object"
								},
								"type": "array"
							},
							"id": {
								"type": "string"
							},
							"limitations": {
								"items": {
									"type": "string"
								},
								"type": "array"
							},
							"name": {
								"type": "string"
							},
							"recipeCategories": {
								"items": {
									"type": "string"
								},
								"type": "array"
							},
							"requiredPower": {
								"type": "number"
							}
						},
						"required": ["id", "available", "recipeCategories", "requiredPower", "features"],
						"type": "object"
					},
					"type": "array"
				},
				"name": {
					"type": "string"
				},
				"recipes": {
					"items": {
						"additionalProperties": false,
						"properties": {
							"available": {
								"type": "boolean"
							},
							"category": {
								"type": "string"
							},
							"craftable": {
								"type": "boolean"
							},
							"duration": {
								"type": "number"
							},
							"id": {
								"type": "string"
							},
							"in": {
								"items": {
									"additionalProperties": false,
									"properties": {
										"amount": {
											"type": "number"
										},
										"id": {
											"type": "string"
										}
									},
									"required": ["id", "amount"],
									"type": "object"
								},
								"type": "array"
							},
							"limitations": {
								"items": {
									"type": "string"
								},
								"type": "array"
							},
							"name": {
								"type": "string"
							},
							"out": {
								"items": {
									"additionalProperties": false,
									"properties": {
										"amount": {
											"type": "number"
										},
										"id": {
											"type": "string"
										}
									},
									"required": ["id", "amount"],
									"type": "object"
								},
								"type": "array"
							},
							"priority": {
								"type": "number"
							}
						},
						"required": ["id", "available", "in", "out", "duration", "category", "priority"],
						"type": "object"
					},
					"type": "array"
				},
				"research": {
					"items": {
						"additionalProperties": false,
						"properties": {
							"id": {
								"type": "string"
							},
							"name": {
								"type": "string"
							},
							"prerequisites": {
								"items": {
									"type": "string"
								},
								"type": "array"
							},
							"unlocks": {
								"items": {
									"additionalProperties": false,
									"properties": {
										"ids": {
											"items": {
												"type": "string"
											},
											"type": "array"
										},
										"type": {
											"const": "recipe",
											"type": "string"
										}
									},
									"required": ["type", "ids"],
									"type": "object"
								},
								"type": "array"
							}
						},
						"required": ["id", "unlocks"],
						"type": "object"
					},
					"type": "array"
				},
				"settings": {
					"additionalProperties": false,
					"properties": {
						"allRecipesUnlocked": {
							"type": "boolean"
						},
						"defaultDuration": {
							"type": "number"
						},
						"limitations": {
							"items": {
								"type": "string"
							},
							"type": "array"
						},
						"nameOverride": {
							"additionalProperties": false,
							"properties": {
								"quality": {
									"type": "string"
								}
							},
							"type": "object"
						}
					},
					"required": ["defaultDuration", "allRecipesUnlocked"],
					"type": "object"
				}
			},
			"required": [
				"id",
				"name",
				"items",
				"recipes",
				"machines",
				"logistics",
				"machineEffects",
				"research",
				"settings"
			],
			"type": "object"
		}
	}
}

=== yabfc/yabfc/profiles/factorio-quality.json
{
	"id": "factorio-quality",
	"name": "Factorio (Vanilla + Quality)",
	"items": [
		{
			"id": "stone-brick",
			"type": "item",
			"category": "terrain",
			"stackSize": 100
		},
		{
			"id": "wood",
			"type": "item",
			"category": "raw-resource",
			"stackSize": 100
		},
		{
			"id": "coal",
			"type": "item",
			"category": "raw-resource",
			"stackSize": 50
		},
		{
			"id": "stone",
			"type": "item",
			"category": "raw-resource",
			"stackSize": 50
		},
		{
			"id": "iron-ore",
			"type": "item",
			"category": "raw-resource",
			"stackSize": 50
		},
		{
			"id": "copper-ore",
			"type": "item",
			"category": "raw-resource",
			"stackSize": 50
		},
		{
			"id": "iron-plate",
			"type": "item",
			"category": "raw-material",
			"stackSize": 100
		},
		{
			"id": "copper-plate",
			"type": "item",
			"category": "raw-material",
			"stackSize": 100
		},
		{
			"id": "copper-cable",
			"type": "item",
			"category": "intermediate-product",
			"stackSize": 200
		},
		{
			"id": "iron-stick",
			"type": "item",
			"category": "intermediate-product",
			"stackSize": 100
		},
		{
			"id": "iron-gear-wheel",
			"type": "item",
			"category": "intermediate-product",
			"stackSize": 100
		},
		{
			"id": "electronic-circuit",
			"type": "item",
			"category": "intermediate-product",
			"stackSize": 200
		},
		{
			"id": "wooden-chest",
			"type": "item",
			"category": "storage",
			"stackSize": 50
		},
		{
			"id": "stone-furnace",
			"type": "item",
			"category": "smelting-machine",
			"stackSize": 50
		},
		{
			"id": "burner-mining-drill",
			"type": "item",
			"category": "extraction-machine",
			"stackSize": 50
		},
		{
			"id": "electric-mining-drill",
			"type": "item",
			"category": "extraction-machine",
			"stackSize": 50
		},
		{
			"id": "burner-inserter",
			"type": "item",
			"category": "inserter",
			"stackSize": 50
		},
		{
			"id": "inserter",
			"type": "item",
			"category": "inserter",
			"stackSize": 50
		},
		{
			"id": "fast-inserter",
			"type": "item",
			"category": "inserter",
			"stackSize": 50
		},
		{
			"id": "long-handed-inserter",
			"type": "item",
			"category": "inserter",
			"stackSize": 50
		},
		{
			"id": "offshore-pump",
			"type": "item",
			"category": "extraction-machine",
			"stackSize": 20
		},
		{
			"id": "pipe",
			"type": "item",
			"category": "energy-pipe-distribution",
			"stackSize": 100
		},
		{
			"id": "boiler",
			"type": "item",
			"category": "energy",
			"stackSize": 50
		},
		{
			"id": "steam-engine",
			"type": "item",
			"category": "energy",
			"stackSize": 10
		},
		{
			"id": "small-electric-pole",
			"type": "item",
			"category": "energy-pipe-distribution",
			"stackSize": 50
		},
		{
			"id": "radar",
			"type": "item",
			"category": "defensive-structure",
			"stackSize": 50
		},
		{
			"id": "small-lamp",
			"type": "item",
			"category": "circuit-network",
			"stackSize": 50
		},
		{
			"id": "pipe-to-ground",
			"type": "item",
			"category": "energy-pipe-distribution",
			"stackSize": 50
		},
		{
			"id": "assembling-machine-1",
			"type": "item",
			"category": "production-machine",
			"stackSize": 50
		},
		{
			"id": "assembling-machine-2",
			"type": "item",
			"category": "production-machine",
			"stackSize": 50
		},
		{
			"id": "red-wire",
			"type": "item",
			"category": "spawnables",
			"stackSize": 1
		},
		{
			"id": "green-wire",
			"type": "item",
			"category": "spawnables",
			"stackSize": 1
		},
		{
			"id": "copper-wire",
			"type": "item",
			"category": "spawnables",
			"stackSize": 1
		},
		{
			"id": "stone-wall",
			"type": "item",
			"category": "defensive-structure",
			"stackSize": 100
		},
		{
			"id": "lab",
			"type": "item",
			"category": "production-machine",
			"stackSize": 10
		},
		{
			"id": "steel-plate",
			"type": "item",
			"category": "raw-material",
			"stackSize": 100
		},
		{
			"id": "engine-unit",
			"type": "item",
			"category": "intermediate-product",
			"stackSize": 50
		},
		{
			"id": "electric-furnace",
			"type": "item",
			"category": "smelting-machine",
			"stackSize": 50
		},
		{
			"id": "solid-fuel",
			"type": "item",
			"category": "raw-material",
			"stackSize": 50
		},
		{
			"id": "rocket-fuel",
			"type": "item",
			"category": "intermediate-product",
			"stackSize": 20
		},
		{
			"id": "iron-chest",
			"type": "item",
			"category": "storage",
			"stackSize": 50
		},
		{
			"id": "big-electric-pole",
			"type": "item",
			"category": "energy-pipe-distribution",
			"stackSize": 50
		},
		{
			"id": "medium-electric-pole",
			"type": "item",
			"category": "energy-pipe-distribution",
			"stackSize": 50
		},
		{
			"id": "steel-furnace",
			"type": "item",
			"category": "smelting-machine",
			"stackSize": 50
		},
		{
			"id": "gate",
			"type": "item",
			"category": "defensive-structure",
			"stackSize": 50
		},
		{
			"id": "steel-chest",
			"type": "item",
			"category": "storage",
			"stackSize": 50
		},
		{
			"id": "solar-panel",
			"type": "item",
			"category": "energy",
			"stackSize": 50
		},
		{
			"id": "train-stop",
			"type": "item",
			"category": "train-transport",
			"stackSize": 10
		},
		{
			"id": "rail-signal",
			"type": "item",
			"category": "train-transport",
			"stackSize": 50
		},
		{
			"id": "rail-chain-signal",
			"type": "item",
			"category": "train-transport",
			"stackSize": 50
		},
		{
			"id": "concrete",
			"type": "item",
			"category": "terrain",
			"stackSize": 100
		},
		{
			"id": "refined-concrete",
			"type": "item",
			"category": "terrain",
			"stackSize": 100
		},
		{
			"id": "hazard-concrete",
			"type": "item",
			"category": "terrain",
			"stackSize": 100
		},
		{
			"id": "refined-hazard-concrete",
			"type": "item",
			"category": "terrain",
			"stackSize": 100
		},
		{
			"id": "landfill",
			"type": "item",
			"category": "terrain",
			"stackSize": 100
		},
		{
			"id": "accumulator",
			"type": "item",
			"category": "energy",
			"stackSize": 50
		},
		{
			"id": "uranium-ore",
			"type": "item",
			"category": "raw-resource",
			"stackSize": 50
		},
		{
			"id": "transport-belt",
			"type": "item",
			"category": "belt",
			"stackSize": 100
		},
		{
			"id": "fast-transport-belt",
			"type": "item",
			"category": "belt",
			"stackSize": 100
		},
		{
			"id": "express-transport-belt",
			"type": "item",
			"category": "belt",
			"stackSize": 100
		},
		{
			"id": "bulk-inserter",
			"type": "item",
			"category": "inserter",
			"stackSize": 50
		},
		{
			"id": "assembling-machine-3",
			"type": "item",
			"category": "production-machine",
			"stackSize": 50
		},
		{
			"id": "underground-belt",
			"type": "item",
			"category": "belt",
			"stackSize": 50
		},
		{
			"id": "fast-underground-belt",
			"type": "item",
			"category": "belt",
			"stackSize": 50
		},
		{
			"id": "express-underground-belt",
			"type": "item",
			"category": "belt",
			"stackSize": 50
		},
		{
			"id": "splitter",
			"type": "item",
			"category": "belt",
			"stackSize": 50
		},
		{
			"id": "fast-splitter",
			"type": "item",
			"category": "belt",
			"stackSize": 50
		},
		{
			"id": "express-splitter",
			"type": "item",
			"category": "belt",
			"stackSize": 50
		},
		{
			"id": "advanced-circuit",
			"type": "item",
			"category": "intermediate-product",
			"stackSize": 200
		},
		{
			"id": "processing-unit",
			"type": "item",
			"category": "intermediate-product",
			"stackSize": 100
		},
		{
			"id": "logistic-robot",
			"type": "item",
			"category": "logistic-network",
			"stackSize": 50
		},
		{
			"id": "construction-robot",
			"type": "item",
			"category": "logistic-network",
			"stackSize": 50
		},
		{
			"id": "passive-provider-chest",
			"type": "item",
			"category": "logistic-network",
			"stackSize": 50
		},
		{
			"id": "active-provider-chest",
			"type": "item",
			"category": "logistic-network",
			"stackSize": 50
		},
		{
			"id": "storage-chest",
			"type": "item",
			"category": "logistic-network",
			"stackSize": 50
		},
		{
			"id": "buffer-chest",
			"type": "item",
			"category": "logistic-network",
			"stackSize": 50
		},
		{
			"id": "requester-chest",
			"type": "item",
			"category": "logistic-network",
			"stackSize": 50
		},
		{
			"id": "rocket-silo",
			"type": "item",
			"category": "space-related",
			"stackSize": 1
		},
		{
			"id": "cargo-landing-pad",
			"type": "item",
			"category": "space-related",
			"stackSize": 1
		},
		{
			"id": "roboport",
			"type": "item",
			"category": "logistic-network",
			"stackSize": 10
		},
		{
			"id": "substation",
			"type": "item",
			"category": "energy-pipe-distribution",
			"stackSize": 50
		},
		{
			"id": "beacon",
			"type": "item",
			"category": "module",
			"stackSize": 20
		},
		{
			"id": "storage-tank",
			"type": "item",
			"category": "storage",
			"stackSize": 50
		},
		{
			"id": "pump",
			"type": "item",
			"category": "energy-pipe-distribution",
			"stackSize": 50
		},
		{
			"id": "pumpjack",
			"type": "item",
			"category": "extraction-machine",
			"stackSize": 20
		},
		{
			"id": "oil-refinery",
			"type": "item",
			"category": "production-machine",
			"stackSize": 10
		},
		{
			"id": "chemical-plant",
			"type": "item",
			"category": "production-machine",
			"stackSize": 10
		},
		{
			"id": "sulfur",
			"type": "item",
			"category": "raw-material",
			"stackSize": 50
		},
		{
			"id": "barrel",
			"type": "item",
			"category": "intermediate-product",
			"stackSize": 10
		},
		{
			"id": "plastic-bar",
			"type": "item",
			"category": "raw-material",
			"stackSize": 100
		},
		{
			"id": "electric-engine-unit",
			"type": "item",
			"category": "intermediate-product",
			"stackSize": 50
		},
		{
			"id": "explosives",
			"type": "item",
			"category": "raw-material",
			"stackSize": 50
		},
		{
			"id": "battery",
			"type": "item",
			"category": "raw-material",
			"stackSize": 200
		},
		{
			"id": "flying-robot-frame",
			"type": "item",
			"category": "intermediate-product",
			"stackSize": 50
		},
		{
